turret_controller:
    type: turret_controller/TurretController

    turret_joint: ['turret_master']

    turret_master:
        type: talon_controllers/TalonMotionMagicCloseLoopController
        joint: shooter_hood_raise
        feedback_type: CTRE_MagEncoder_Absolute
        close_loop_values:
            - {p: 2.0, i: 0.002, d: 0.0, f: 1.0, i_zone: 0}
        invert_output: true
        sensor_phase: false
        peak_output_forward: 1.0
        peak_output_reverse: -1.0
        nominal_output_forward: 0.0
        nominal_output_reverse: 0.0
        motion_cruise_velocity: 20
        motion_acceleration: 100
        voltage_compensation: true
        dynamic_reconfigure: true
        #Edit once we know what these do
        #limit_switch_local_reverse_source: "FeedbackConnector"
        #limit_switch_local_reverse_normal: "NormallyOpen"
        softlimit_forward_threshold: 1 #Incorrect placeholder value
        softlimit_forward_enable: false

