swerve_drive_controller:
    steering_joint_bl:
        offset: -3.93619
    steering_joint_br:
        offset: 1.83464
    steering_joint_fl:
        offset: -2.2795
    steering_joint_fr:
        offset: 3.66928
