field_dims:
  width: 360
  height: 180

imagename: "slalom_path.png"

obstacles:
  - {type: "circle", center: [300, 60], radius: 3.0}
  - {type: "polygon", num_points: 4, p1: [118, 58], p2: [118, 62], p3: [242, 62], p4: [242, 58]}
  - {type: "circle", center: [30,  60], radius: 2.0}
  - {type: "circle", center: [60,  60], radius: 2.0}
  - {type: "circle", center: [30, 120], radius: 2.0}
  - {type: "circle", center: [60, 120], radius: 2.0}

