field_dims:
  width: 360
  height: 180

imagename: "slalom_path.png"

obstacles:
  - {type: "circle", center: [300, 60], radius: 40.0}
  - {type: "polygon", num_points: 4, p1: [120, 50], p2: [120, 70], p3: [240, 70], p4: [240, 50]}
