# params/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---

camera_model: 'zedm'

# Dynamic parameters cannot have a namespace

depth:
    min_depth:                  0.35            # Min: 0.1, Max: 3.0 - Default 0.3 - Note: reducing this value will require MUCH MORE computational power and RAM memory
    max_depth:                  10.0            # Max: 20.0

tracking:
    imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only the optical odometry will be used.

imu:
    imu_frame:                  'zed_imu_link'  # must be equal to the frame_id used in the URDF file
    imu_pub_rate:               400.0           # max value 800 Hz
    imu_timestamp_sync:         false           # Synchronize IMU message timestamp with latest received frame
