#Config file for configuring autonomous modes and actions

# MODES - arrays of actions (see below) that will be executed in order

auto_mode_1: ["align_to_shoot", "pause_2_sec"] #example
auto_mode_2: []


# ACTIONS - must have a value for "type", other stuff varies

#valid action types: "intake_actionlib_server", "pause"

#examples:

align_to_shoot:
    type: "intake_actionlib_server"
    goal:
        "placeholder"
        # action goal items

pause_2_sec:
    type: "pause"
    duration: 2 #sec
