#Config file for configuring autonomous modes and actions

# CONSTANTS -----------------------------------------------------------------------
goal_to_wall_y_dist: 2.404

# MODES ---------------------------------------------------------------------------
# arrays of actions (see below) that will be executed in order
# format: auto_mode_[integer]: array
#
auto_mode_1: ["tuning"]
auto_mode_2: ["map_relative_barrel_racing_path"]
auto_mode_3: ["map_relative_bounce_path"]
auto_mode_4: ["map_relative_slalom_path"]
auto_mode_5: ["dynamic_path"]
auto_mode_6: ["galactic_search_path"]

#auto_mode_1: ["start_intake", "path_to_trench_face_goal", "stop_intake", "shoot", "pause_2_sec"] #example
#auto_mode_2: ["pause_2_sec","pause_5_sec"]
#auto_mode_3: ["drive_back", "path_to_trench_after_drive_back"]
#auto_mode_4: ["drive_back", "shoot", "path_to_trench_after_drive_back"]
#auto_mode_5: ["drive_test_angle", "start_intake", "drive_forward", "stop_intake"]
#auto_mode_6: ["drive_path_test_1"]

# ACTIONS ------------------------------------------------------------------------
# must have a value for "type", other stuff varies
#valid action types: "intake_actionlib_server", "pause", "elevator_actionlib_server"

tuning:
  type: "path"
  goal:
    apply_offset: false
    points:
      - [1.0, 0.0, 0.0]
      - [2.0, 2.0, 0.0]
      - [3.0, 1.0, 0.0]

map_relative_barrel_racing_path:
  type: "path"
  goal:
    apply_offset: false
    points:
      - [5.25, 2.29, 0.0]
      - [3.81, 0.46, 0.0]
      - [1.98, 2.29, 0.0]
      - [5.50, 2.29, 0.0]
      - [8.69, 3.00, 0.0]
      - [6.10, 3.75, 0.0]
      - [4.57, 3.05, 0.0]
      - [7.62, 0.46, 0.0]
      - [8.65, 2.29, 0.0]
      - [6.20, 2.29, 0.0]
      - [0.76, 2.29, 0.0]
    frame_id: "map"

map_relative_bounce_path:
  type: "path"
  goal:
    apply_offset: false
    points:
        #- [2.29, 3.81, 0.0]
        #- [1.16, 3.36, 0.0]
        #- [3.35, 0.76, 0.0]
        #- [4.27, 0.76, 0.0]
        #- [4.57, 3.81, 0.0]
        #- [4.88, 0.76, 0.0]
        #- [6.71, 0.76, 0.0]
        #- [6.86, 3.81, 0.0]
        #- [8.38, 2.29, 0.0]
        - [1.397, 2.286, 0.0]
        - [1.651, 2.921, 0.0]
        - [2.54, 1.27, 0.0]
        - [3.175, 0.635, 0.0]
        - [3.81, 1.27, 0.0]
        - [3.556, 2.794, 0.0]
        - [4.064, 1.27, 0.0]
        - [4.6355, 0.635, 0.0]
        - [5.461, 1.27, 0.0]
        - [5.461, 2.794, 0.0]
        - [5.969, 2.032, 0.0]
        - [7.62, 1.905, 0.0]
    frame_id: "map"
    point_frame_id: []
    path_offset_limit:
      - {min_x: 0, max_x: 0, min_y: 0, max_y: 0}
    optimize_final_velocity: true
    iteration: 1

map_relative_slalom_path:
  type: "path"
  goal:
    apply_offset: false
    points:
      - [2.29, 2.29, 0.0]
      - [6.86, 2.29, 0.0]
      - [6.86, 0.76, 0.0]
      - [8.38, 0.76, 0.0]
      - [8.38, 2.29, 0.0]
      - [6.86, 2.29, 0.0]
      - [6.86, 0.76, 0.0]
      - [2.29, 0.76, 0.0]
      - [0.76, 2.29, 0.0]
    frame_id: "map"
    point_frame_id: []
    path_offset_limit:
      - {min_x: 0, max_x: 0, min_y: 0, max_y: 0}
    optimize_final_velocity: true
    iteration: 1


#examples:

start_intake:
    type: "intake_actionlib_server"
    goal:
        "start"

stop_intake:
    type: "intake_actionlib_server"
    goal:
        "stop"

shoot:
    type: "shooter_actionlib_server"
    goal:
        ""

drive_back:
    type: "path"
    goal:
        apply_offset: false
        points:
            - [-0.7, 0.0, 0.0] # move back length of robot

path_to_trench_from_starting:
    type: "path"
    goal:
        apply_offset: true
        points:
            - [-3.0, -1.69938, 0.0] #from starting position to in front of the trench
            - [-4.2, -1.69938, 0.0] #drive toward the trench distance of 2 balls

path_to_trench_after_drive_back:
    type: "path"
    goal:
        apply_offset: true
        points:
            - [-2.3, -1.69938, 0.0]
            - [-3.5, -1.69938, 0.0]

pause_2_sec:
    type: "pause"
    duration: 2 #sec

pause_5_sec:
    type: "pause"
    duration: 5.0

drive_test_angle:
    type: "path"
    goal:
        apply_offset: false
        points:
            - [1.0, -1.0, 0.0]
            - [2.0, 0.0, 0.0]

drive_forward:
    type: "path"
    goal:
        apply_offset: false
        points:
            - [1.5, 0.0, 0.0]


drive_path_test_1:
  type: "path"
  goal:
    apply_offset: false
    points:
      - [1.0, 0.0, 0.0]
      - [2.0, 3.0, 0.0]
      - [1.0, 4.0, 0.0]
    frame_id: ""
    point_frame_id: []
    path_offset_limit:
      - {min_x: 0, max_x: 0, min_y: 0, max_y: 0}
    optimize_final_velocity: true
