#Config file for configuring autonomous modes and actions

# MODES ---------------------------------------------------------------------------
# arrays of actions (see below) that will be executed in order
# format: auto_mode_[integer]: array

auto_mode_1: ["start_intake", "path_to_trench_face_goal", "stop_intake", "shoot", "pause_2_sec"] #example
auto_mode_2: ["start_intake", "pause_2_sec", "stop_intake", "pause_5_sec"]
auto_mode_3: ["path_to_trench_face_goal", "pause_2_sec"]


# ACTIONS ------------------------------------------------------------------------
# must have a value for "type", other stuff varies
#valid action types: "intake_actionlib_server", "pause", "elevator_actionlib_server"

#examples:

start_intake:
    type: "intake_actionlib_server"
    goal:
        "start"

stop_intake:
    type: "intake_actionlib_server"
    goal:
        "stop"

shoot:
    type: "shooter_actionlib_server"
    goal:
        ""

path_to_trench_face_goal:
    type: "path"
    goal:
        points:
            - [1.0, 1.0, 3.14159]
            - [2.0, 2.0, 6.28]

drive_test:
    type: "path"
    goal:
        points:
            - [0.5, 0.0, 0.0]
            - [-0.5, 0.0, 0.0]

pause_2_sec:
    type: "pause"
    duration: 2 #sec

pause_5_sec:
    type: "pause"
    duration: 5.0
