noise_delta_t: 1.0

field_dims:
  x_min: -1.0
  x_max:  6.0
  y_min: -1.0
  y_max:  4.0

init_dims:
  x_min: 0.0
  x_max: 2.5
  y_min: 0.0
  y_max: 4.0

num_particles: 200

noise_stdev:
  position: 0.1
  rotation: 0.1

beacons:
  - [-1.0, 0.0]
  - [-1.0, 0.5]
  - [-1.0, 1.0]
  - [-1.0, 1.5]
  - [-1.0, 2.0]
  - [-1.0, 2.5]
