noise_delta_t: 1.0

field_dims:
  x_min: 0.0
  x_max: 9.144
  y_min: 0.0
  y_max: 4.572

init_dims:
  x_min: 0.0
  x_max: 1.524
  y_min: 0.0
  y_max: 3.048

num_particles: 200

noise_stdev:
  position: 0.02
  rotation: 0.01

beacons:
  - [-1.72, -0.2, "1"]
  - [-1.72, 0.48, "0"]
  - [-1.72, 1.145, "2"]
  - [-1.72, 1.638, "4"]
  - [-1.72, 2.263, "5"]
  - [-1.72, 3.103, "3"]
