noise_delta_t: 1.0

field_dims:
  x_min: 0.0
  x_max: 4.572
  y_min: 0.0
  y_max: 9.144

init_dims:
  x_min: 0.0
  x_max: 3.048
  y_min: 0.0
  y_max: 1.524

num_particles: 200

noise_stdev:
  position: 0.02
  rotation: 0.02

beacons:
  - [-0.2, -1.655, "1"]
  - [0.48, -1.655, "0"]
  - [1.145, -1.655, "2"]
  - [1.638, -1.655, "4"]
  - [2.263, -1.655, "5"]
  - [3.103, -1.655, "3"]
