field_dims:
  x_min: 0
  x_max: 4
  y_min: 0
  y_max: 4

init_dims:
  x_min: 0
  x_max: 4
  y_min: 0
  y_max: 4

num_particles: 100

noise_stdev:
  position: 0.1
  rotation: 0.1

beacons:
  - [1, 3]
  - [2, 3]
  - [3, 4]
