name: ROSBuild

on:
  push:
    branches:
      - gh_actions

env:
  BUILD_TYPE: Release

jobs:

  # Check out the code. This executes directly on the VM. 
  build:
    runs-on: self-hosted
    container: frc900/zebros-2021-dev:latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: '2020Offseason'
          ref: "gh_actions"
          submodules: 'recursive'
      
        - name: Install wstools
          run: |
            wstool update -t src
            source ROSStandard.sh
        
        - name: Build
          run: natbuild
